# Generated by Django 5.2.15 on 2026-07-06 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="admin_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Rescheduled", "Rescheduled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
