# Generated by Django 5.2.15 on 2026-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0003_reservation_admin_message_alter_reservation_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="admin_message",
            field=models.TextField(
                blank=True, help_text="Message to send to the customer."
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Rescheduled", "Rescheduled"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
