# Generated by Django 5.2.15 on 2026-07-08 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_alter_reservation_admin_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
