# Generated by Django 5.2.15 on 2026-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash / Pay at Restaurant"),
                    ("online", "Pay Online"),
                ],
                default="cash",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ready_time",
            field=models.DateTimeField(
                blank=True, help_text="Expected pickup or delivery time", null=True
            ),
        ),
    ]
